name: Run Node Callback
description: Run a node callback
inputs:
  nodeVersionFile:
    description: 'Node Version File'
    required: true
    default: '.nvmrc'
  onDeployScript:
    description: 'On Deploy Script'
    required: true
    default: 'on_deploy'
  args:
    description: 'Arguments'
    required: false
    default: ''
  workingDirectory:
    description: 'Working directory'
    required: false
    default: '.'

defaults:
  run:
    working-directory: ${{ inputs.workingDirectory }}
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install Node Using .nvmrc
      uses: actions/setup-node@v2
      with:
        node-version-file: ${{ inputs.nodeVersionFile }}
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Compile to javascript files
      shell: bash
      run: npm run build
    - name: Run Node on_deploy Callback In Main.ts
      shell: bash
      run: |
        npm run ${{ inputs.onDeployScript }} ${{ inputs.args }}